version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  target-branch: "develop"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "12:00"
    timezone: "Asia/Tokyo"
